#### /usr/bin/Rscript
#
#
#
# This is an R script for visualizing the number of ASVs predicted present for functions
# in FAPROTAX2-mapper vs. FAPROTAX1.
#
#
# Rob Porch
# last updated 2026 March 19

###################
# Load packages
library(tidyverse)
library(data.table)
library(readxl)
library(showtext)
library(extrafont)
library(optparse)
####################


####################
# Set up command-line arguments

option_list <- list(
	make_option(c("-a", "--in_ASV_table"), type="character", default="", help="Path to ASV table listing ASVs present in each sample."),
	make_option("--in_faprotax1_table", type="character", default="", help="Path to function table generated by FAPROTAX v1."),
	make_option("--in_faprotax2_table", type="character", default="", help="Path to function table generated by FAPROTAX2-mapper."),
	make_option("--in_sample_metadata", type="character", default="", help="Path to Excel file listing metadata on microbiome samples."),
	make_option(c("-o", "--out_figure"), type="character", default="", help="Path to store output figure showing boxplots of ASVs with predicted presence."),
	make_option("--out_table", type="character", default="", help="Path to store output table listing differences in number of ASVs with predicted presence.")
)

# Parse command-line arguments
opt <- parse_args(optparse::OptionParser(option_list = option_list))



###################
# Main script body
###################

asv_table <- data.table::fread(opt$in_ASV_table, header = TRUE)
faprotax1 <- data.table::fread(opt$in_faprotax1_table, header = TRUE)
faprotax2 <- data.table::fread(opt$in_faprotax2_table, header = TRUE)
sample_metadata <- readxl::read_xlsx(opt$in_sample_metadata)

names(sample_metadata) <- c("SampleID", "sample_type")

asv_long <- asv_table %>%
  pivot_longer(-1, names_to = "SampleID", values_to = "Abundance") %>%
  rename(ASV = 1) %>%
  filter(Abundance > 0)

# prepare faprtoax1
faprotax1_long <- faprotax1 %>%
  separate_rows(group, sep = ",") %>%
  rename(ASV = record, Trait = group) %>%
  mutate(Tool = "FAPROTAX v1")

# prepare faprotax2
faprotax2_long <- faprotax2 %>%
  pivot_longer(-OTU, names_to = "Trait", values_to = "Presence") %>%
  filter(Presence == 1) %>%
  rename(ASV = OTU) %>%
  mutate(Tool = "FAPROTAX2-mapper")

# combine faprotax1 and faprotax2
faprotax_combined <- bind_rows(faprotax1_long %>% select(ASV, Trait, Tool),
                               faprotax2_long %>% select(ASV, Trait, Tool))

# join ASV abundance data with faprotax predictions
asv_trait_sample <- asv_long %>%
  select(ASV, SampleID) %>%
  inner_join(faprotax_combined, by = "ASV")

# filter traits shared between both faprotax versions
shared_traits <- asv_trait_sample %>%
  group_by(Trait, Tool) %>%
  summarize(n = n(), .groups = "drop") %>%
  count(Trait) %>%
  filter(n == 2) %>%
  pull(Trait)

asv_trait_sample_shared <- asv_trait_sample %>%
  filter(Trait %in% shared_traits)

# count number of ASVs per trait, per sample, per faprotax version
trait_counts <- asv_trait_sample_shared %>%
  inner_join(sample_metadata, by = "SampleID") %>%
  group_by(sample_type, Tool, Trait) %>%
  summarize(ASV_Count = n_distinct(ASV), .groups = "drop")

trait_counts$sample_type <- gsub("_", " ", trait_counts$sample_type)

trait_counts_wide <- trait_counts %>%
  pivot_wider(values_from=ASV_Count,
              names_from=Tool) 

ASVs_scatterplots <- ggplot(trait_counts_wide, aes(x=(`FAPROTAX v1`), y=(`FAPROTAX2-mapper`))) +
	geom_point(size=1.5, alpha=0.7, color="#4287f5") +
	geom_abline(slope=1, intercept=0, linetype="dashed", color="grey50", linewidth=0.5) +
	scale_x_log10() + scale_y_log10() +
	facet_wrap(~sample_type, scales="free", nrow=3,
				labeller = labeller(sample_type = label_wrap_gen(width = 15))) +
	theme_classic(base_size=7) +
	labs(title="ASVs with predicted presence", x="Number of ASVs (FAPROTAX v1)", y="Number of ASVs (FAPROTAX2-mapper)") +
	theme(
		strip.text=element_text(size=8),
		strip.background=element_blank(),
		axis.text=element_text(size=7),
		panel.background=element_rect(fill=NA, color="black", linewidth=1),
		panel.spacing=unit(0.5, "lines"),
		axis.line=element_blank(),
		axis.title.y=element_text(size=9),
		axis.title.x=element_text(size=9),
		title.text=element_text(size=7)
	)
	
ggsave(opt$out_figure, ASVs_scatterplots, width = 5, height = 6)
data.table::fwrite(trait_counts_wide, opt$out_table, sep="\t")